---
  title: "Lecture Materials"
  output: 
    html_document:
      toc: true
      toc_depth: 3
      toc_float: true
      self_contained: true
      df_print: paged
      mathjax: default
  bibliography: eco104_books.bib  
  link-citations: yes
  linkcolor: blue
---
  


Here are the slides for the lectures. The slides are in pdf format. You can download them and use them offline.

# Chapter 1

- **Slides :** [Ch1 - Descriptive Statistics](slides/Ch1/01_desc_stats.pdf)
- **DataSets** Following are the data sets used in Ch1 Slides, most of the data sets are from @anderson_statistics_2020. You can download them and use them for practice.

  - [Audit Data](slides/Ch1/data_sets/Audit.xlsx)
  - [Boxplot Data](slides/Ch1/data_sets/Boxplot_Data.xlsx)
  - [Commercials Sales Data](slides/Ch1/data_sets/Commercials_Sales.xlsx)
  - [Covariance and Correlation Data](slides/Ch1/data_sets/Cov_Corr_Data.xlsx)
  - [Geometric Mean Data](slides/Ch1/data_sets/GeomMean.xlsx)
  - [Hand Data](slides/Ch1/data_sets/HandData.xlsx)
  - [Heights Data](slides/Ch1/data_sets/Heights.xlsx)
  - [Hypothetical EWU Data](slides/Ch1/data_sets/Hypothetical_EWU_Data.xlsx)
  - [Restaurant Data](slides/Ch1/data_sets/Restaurant.xlsx)
  - [Soft Drink Data](slides/Ch1/data_sets/SoftDrink.xlsx)
  - [Supply Days Data](slides/Ch1/data_sets/Supply_Days.xlsx)
  
- **Key concepts are:** What is Statistics? What is data? Different types of data, Different Classifications of Variables (Categorial vs Quantitative, Discrete vs Continuous, Nominal, Ordinal, Interval, Ratio), What is Population and Sample? How to do Sampling? Tabular and Graphical Measures - Frequency Distribution, Bar Chart, Histogram, Box-Plot, Scatter-Plot, and so on. Numerical Measures - Mean, Pecentile, Median, Variance and Standard Deviation, Covariance and Correlation, Geometric Mean, and so on.


# Chapter 2

- **Slides :** [Ch2 - Probability](slides/Ch2/02_prob_theory_1.pdf) 
- **Recap Slides :** [Ch0 - Math Recap](slides/Ch2/00_math_recap_1.pdf)


- **Key concepts are:** Definitions of Random Experiment, Sample Space, Event and Probability? Different approaches to define Probability - Classical, Relative Frequency, and Axiomatic. Basic Probability Rules - Addition Rule, Multiplication Rule, Conditional Probability, Bayes' Theorem, and so on.

- **Note:** The math recap slides are only to brush up your old math knowledge. You can skip them if you are comfortable with basic math concepts like set theory, functions, permutations, combinations, and so on.





<br>




# **References**

<div id="refs"></div>

<div style="height:10cm;"></div>



