---
  title: "Problem Sets"
  output: 
    html_document:
      toc: true
      toc_depth: 3
      toc_float: true
      self_contained: true
      df_print: paged
      mathjax: default
  bibliography: eco104_books.bib  
  link-citations: yes
  linkcolor: blue
---
  
Pleas submit the problem set in **PDF** format within the **specified deadline** in google classroom. If you use Excel to solve the problem set, please submit the **Excel file**  file as well.

## Problem Set 1

- **Deadline**: 9th July, 2025
- [PS1 Question](problem_sets/ps1/PS_1.pdf)
    - [Question-1 Data File](problem_sets/ps1/DataFiles/question-1.xlsx)
    - [Question-2 Data File](problem_sets/ps1/DataFiles/question-2.xlsx)
    - [Question-3 Data File](problem_sets/ps1/DataFiles/question-3.xlsx)
    - [Question-4 Data File](problem_sets/ps1/DataFiles/question-4.xlsx)
    - [Question-6 Data File](problem_sets/ps1/DataFiles/question-6.xlsx)
    - [Question-7 Data File](problem_sets/ps1/DataFiles/question-7.xlsx)
    
- [PS1 Solution]() : We haven't provided the solution to the problem set. 

## Problem Set 2

- **Deadline**: 3rd Aug (Sec 9) and 4th Aug (Sec 7), In class hard copy submission

- [PS2 Question](problem_sets/ps2/PS_2.pdf)

- [PS2 Solution]() : The solution will be provided after the deadline, so please 


## Problem Set 3

- [PS3 With Solution](problem_sets/ps3/PS_3_soln.pdf): You don't need to submit, but please solve it before Mid - 2 


<div style="height:10cm;"></div>

